# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "labels", # <outlierplot>
  "x", # <outlierplot>
  "y", # <outlierplot>
  "alpha", # <outlierplot>
  "labels", # <outlierplotold>
  "x", # <outlierplotold>
  "y", # <outlierplotold>
  "alpha", # <outlierplotold>
  NULL
))
