# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "x", # <allmethods>
  "y", # <allmethods>
  "labels", # <outlierplot>
  "x", # <outlierplot>
  "y", # <outlierplot>
  "alpha", # <outlierplot>
  "distance", # <outlierplot>
  "df.distance", # <outlierplot>
  NULL
))
